[package]
name = "assets"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
serde_ron = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
utils = { path = "../utils", version = "0.1.0" }