[package]
name = "assets"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
utils = { path = "../utils", version = "0.1.0" }
serde = { version = "1", features = ["derive", "rc"] }
serde_ron = { version = "0.8", package = "ron" }
thiserror= "*"